# Generated by Django 5.2.7 on 2025-11-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_projet_equipe_projet_statut_alter_projet_manager'),
        ('taches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='collaborateur',
            field=models.ForeignKey(limit_choices_to={'role': 'collaborateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='collaborateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='projets.projet'),
        ),
    ]
