# Generated by Django 5.2.7 on 2025-11-05 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='equipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
