# Generated by Django 5.2.7 on 2025-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0002_equipe_membres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='membres',
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.CharField(null=True),
        ),
    ]
