# Generated by Django 5.2.7 on 2025-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_projet_equipe_projet_statut_alter_projet_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='nombre_projet',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='projet_encours',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='projet_termines',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='taux_avancement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
